### ISSUE TITLE
Applicable to other openFOAM versions

### ISSUE THREAD

**Issue by whhjken1** [arnaupv/avgCyclicDir#1]
Hi Arnau,

    Recently I have been trying to compile your tool with OpenFOAM 4.x and OpenFOAM 6, but without any success. There are some syntactics errors. I was wondering if your could revise the codes and make it compatible with openFOAM version 6. Thanks a lot.

Best regards,

Han

**Comment by arnaupv** [comment]
The project has a new branch called openFoam-4.1, which is compatible with this openFoam version. Please check it out with 4.x and 6 and provide some feedback.

**Comment by whhjken1** [comment]
I have tested the new branch, it works well in both OpenFOAM 4.x and 6, thanks for your kind reply.
