### ISSUE TITLE
OpenFOAM-1706 compatibility

### ISSUE THREAD

**Issue by ghost** [arnaupv/avgCyclicDir#3]
Hello, 

I have a problem to compile avgCyclicDir in OpenFOAM 1706. Here is the output: 

dradenkovic@dradenkovic:~/OpenFOAM/dradenkovic-v1706/avgCyclicDir$ ./Allwmake
wmake extrude2DMesh
wmakeLnInclude: linking include files to ./lnInclude
Making dependency list for source file patchToPoly2DMesh.C
Making dependency list for source file extrude2DMesh.C
g++ -std=c++11 -m64 -DOPENFOAM_PLUS=1706 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/meshTools/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/dynamicMesh/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/finiteVolume/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/surfMesh/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/mesh/extrudeModel/lnInclude -IlnInclude -I. -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/OpenFOAM/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/OSspecific/POSIX/lnInclude   -fPIC -c extrude2DMesh/extrude2DMesh.C -o Make/linux64GccDPInt32Opt/extrude2DMesh/extrude2DMesh.o
g++ -std=c++11 -m64 -DOPENFOAM_PLUS=1706 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/meshTools/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/dynamicMesh/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/finiteVolume/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/surfMesh/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/mesh/extrudeModel/lnInclude -IlnInclude -I. -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/OpenFOAM/lnInclude -I/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/src/OSspecific/POSIX/lnInclude   -fPIC -c patchToPoly2DMesh/patchToPoly2DMesh.C -o Make/linux64GccDPInt32Opt/patchToPoly2DMesh/patchToPoly2DMesh.o
patchToPoly2DMesh/patchToPoly2DMesh.C: In member function ‘void Foam::patchToPoly2DMesh::addPatchFacesToOwner()’:
patchToPoly2DMesh/patchToPoly2DMesh.C:175:36: error: ‘const class Foam::MeshedSurface<Foam::face>’ has no member named ‘faces’
     const faceList& faces = patch_.faces();
                                    ^
/home/dradenkovic/OpenFOAM/OpenFOAM-v1706/wmake/rules/General/transform:28: recipe for target 'Make/linux64GccDPInt32Opt/patchToPoly2DMesh/patchToPoly2DMesh.o' failed

Does this seems familiar to you? What could be the problem? 

Regards, 
Darko

**Comment by arnaupv** [comment]
Hi, try this as a quick patch :) Let me know if it works.
```
cd ~/OpenFOAM/dradenkovic-v1706/avgCyclicDir
./Allwclean
git checkout 6f34f2386af6486a9dc889a0c37d8a2ebf49eda6
./Allwclean
./Allwmake
```

Cheers

**Comment by ghost** [comment]
It works! Thank you. 

Regards, 
Darko
